# Generated by Django 6.0.2 on 2026-03-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="added_at",
            new_name="created_at",
        ),
    ]
